// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBotApi.Data;

#nullable disable

namespace TelegramBotApi.Migrations
{
    [DbContext(typeof(TMKDbContext))]
    [Migration("20251006134857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TelegramBotApi.Entities.Nomenclature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Koef")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PipeWallThickness")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteelGrade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nomenclatures");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Price", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdStock")
                        .HasColumnType("TEXT");

                    b.Property<int>("NDS")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PriceLimitM1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceLimitM2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceLimitT1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceLimitT2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceM")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceM1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceM2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceT")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceT1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceT2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "IdStock");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Remnant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdStock")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgTubeLength")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgTubeWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InStockM")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InStockT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "IdStock");

                    b.ToTable("Remnants");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Stock", b =>
                {
                    b.Property<Guid>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdStock");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
