// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelegramBotApi.Data;

#nullable disable

namespace TelegramBotApi.Migrations
{
    [DbContext(typeof(TMKDbContext))]
    [Migration("20251006191749_AddOrderAndOrderItem")]
    partial class AddOrderAndOrderItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TelegramBotApi.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<long>("NomenclatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("StockId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Nomenclature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Koef")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PipeWallThickness")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteelGrade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nomenclatures");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("NomenclatureId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StockId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Price", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdStock")
                        .HasColumnType("TEXT");

                    b.Property<int>("NDS")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PriceLimitM1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceLimitM2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceLimitT1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceLimitT2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceM")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceM1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceM2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceT")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceT1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceT2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "IdStock");

                    b.HasIndex("IdStock");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Remnant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdStock")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgTubeLength")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgTubeWeight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InStockM")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InStockT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "IdStock");

                    b.HasIndex("IdStock");

                    b.ToTable("Remnants");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Stock", b =>
                {
                    b.Property<Guid>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseCode")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStock");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.CartItem", b =>
                {
                    b.HasOne("TelegramBotApi.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotApi.Entities.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotApi.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Nomenclature");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Order", b =>
                {
                    b.HasOne("TelegramBotApi.Entities.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.OrderItem", b =>
                {
                    b.HasOne("TelegramBotApi.Entities.Nomenclature", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotApi.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotApi.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Order");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Price", b =>
                {
                    b.HasOne("TelegramBotApi.Entities.Nomenclature", "Nomenclature")
                        .WithMany("Prices")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotApi.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("IdStock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Remnant", b =>
                {
                    b.HasOne("TelegramBotApi.Entities.Nomenclature", "Nomenclature")
                        .WithMany("Remnants")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBotApi.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("IdStock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Nomenclature", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Remnants");
                });

            modelBuilder.Entity("TelegramBotApi.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
